ORG 30H
	DIVIDEND: DB 1  ;被除數
	DIVISOR: DB 1  ;除數
	QUOTIENT: DB 1  ;商
	REMAINDER: DB 1  ;餘數

ORG 0000H
	MOV DIVIDEND, #48H  ;設定 DIVIDEND 值
	MOV DIVISOR, #10H  ;設定 DIVISOR 值

	DIV8: MOV A, DIVIDEND  ;A 放 DIVIDEND 的值
	MOV B, DIVISOR  ;B 放 DIVISOR 的值
	DIV AB  ;A, B相除
	MOV QUOTIENT, A  ;QUOTIENT 放 A, B相除的商 A
	MOV REMAINDER, B  ;REMAINDER 放 A, B相除的餘數 B
	
	RET
END
