ORG 30H
	MINUEND: DB 1  ;被減數
	SUBEND: DB 1  ;減數
	RESULT: DB 1  ;結果

ORG 0000H
	MOV MINUEND, #83H  ;設定 MINUEND 值
	MOV SUBEND, #43H  ;設定 SUBEND 值

	ADD8: MOV A, MINUEND  ;A 放 MINUEND 的值
	SUBB A, SUBEND  ;A <- A - SUBEND 的值
	MOV RESULT, A  ;RESULT 放 A 的值
	
	RET
END
